# Site settings
title: Blog
email: ashleighmcclure@ymail.com
description: > # this means to ignore newlines until "baseurl:"
  Want to know about current fashion, literature, and more? This is the place.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ashleighmcclure.github.io" # the base hostname & protocol for your site
twitter_username: mcclureashleigh
github_username:  ashleighmcclure

# Build settings
markdown: kramdown
